home=c:\bc
cc=$(home)\bin\bcc
link=$(home)\bin\tlink
pck=upx
lib=$(home)\lib
cflags=-c -mt
lflags=-t -x -L$(lib)
prg=c3
source=$(prg).c
object=$(prg).obj
target=$(prg).com

all: $(target)

$(target): $(source)
	$(cc) $(cflags) $(source)
	$(link) $(lflags) c0t.obj $(object),$(target),,cs.lib
	$(pck) -9 $(target)

clean:
	erase c3.com
	erase c3.map
	erase c3.obj
